// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateOrderRequest_OrderType int32

const (
	CreateOrderRequest_Market CreateOrderRequest_OrderType = 0
	CreateOrderRequest_Limit  CreateOrderRequest_OrderType = 1
)

var CreateOrderRequest_OrderType_name = map[int32]string{
	0: "Market",
	1: "Limit",
}
var CreateOrderRequest_OrderType_value = map[string]int32{
	"Market": 0,
	"Limit":  1,
}

func (x CreateOrderRequest_OrderType) String() string {
	return proto.EnumName(CreateOrderRequest_OrderType_name, int32(x))
}
func (CreateOrderRequest_OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{4, 0}
}

type CreateOrderRequest_OrderSide int32

const (
	CreateOrderRequest_Buy  CreateOrderRequest_OrderSide = 0
	CreateOrderRequest_Sell CreateOrderRequest_OrderSide = 1
)

var CreateOrderRequest_OrderSide_name = map[int32]string{
	0: "Buy",
	1: "Sell",
}
var CreateOrderRequest_OrderSide_value = map[string]int32{
	"Buy":  0,
	"Sell": 1,
}

func (x CreateOrderRequest_OrderSide) String() string {
	return proto.EnumName(CreateOrderRequest_OrderSide_name, int32(x))
}
func (CreateOrderRequest_OrderSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{4, 1}
}

type ExecutionReport_OrderState int32

const (
	ExecutionReport_Booked    ExecutionReport_OrderState = 0
	ExecutionReport_Rejected  ExecutionReport_OrderState = 1
	ExecutionReport_Partial   ExecutionReport_OrderState = 2
	ExecutionReport_Filled    ExecutionReport_OrderState = 3
	ExecutionReport_Cancelled ExecutionReport_OrderState = 4
)

var ExecutionReport_OrderState_name = map[int32]string{
	0: "Booked",
	1: "Rejected",
	2: "Partial",
	3: "Filled",
	4: "Cancelled",
}
var ExecutionReport_OrderState_value = map[string]int32{
	"Booked":    0,
	"Rejected":  1,
	"Partial":   2,
	"Filled":    3,
	"Cancelled": 4,
}

func (x ExecutionReport_OrderState) String() string {
	return proto.EnumName(ExecutionReport_OrderState_name, int32(x))
}
func (ExecutionReport_OrderState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{11, 0}
}

type ExecutionReport_ReportType int32

const (
	ExecutionReport_Status ExecutionReport_ReportType = 0
	ExecutionReport_Fill   ExecutionReport_ReportType = 1
)

var ExecutionReport_ReportType_name = map[int32]string{
	0: "Status",
	1: "Fill",
}
var ExecutionReport_ReportType_value = map[string]int32{
	"Status": 0,
	"Fill":   1,
}

func (x ExecutionReport_ReportType) String() string {
	return proto.EnumName(ExecutionReport_ReportType_name, int32(x))
}
func (ExecutionReport_ReportType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{11, 1}
}

type InMessage struct {
	// Types that are valid to be assigned to Request:
	//	*InMessage_Login
	//	*InMessage_Create
	//	*InMessage_Modify
	//	*InMessage_Cancel
	//	*InMessage_Massquote
	//	*InMessage_Secdefreq
	//	*InMessage_Download
	Request              isInMessage_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InMessage) Reset()         { *m = InMessage{} }
func (m *InMessage) String() string { return proto.CompactTextString(m) }
func (*InMessage) ProtoMessage()    {}
func (*InMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{0}
}
func (m *InMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InMessage.Unmarshal(m, b)
}
func (m *InMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InMessage.Marshal(b, m, deterministic)
}
func (dst *InMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InMessage.Merge(dst, src)
}
func (m *InMessage) XXX_Size() int {
	return xxx_messageInfo_InMessage.Size(m)
}
func (m *InMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InMessage proto.InternalMessageInfo

type isInMessage_Request interface {
	isInMessage_Request()
}

type InMessage_Login struct {
	Login *LoginRequest `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type InMessage_Create struct {
	Create *CreateOrderRequest `protobuf:"bytes,2,opt,name=create,proto3,oneof"`
}

type InMessage_Modify struct {
	Modify *ModifyOrderRequest `protobuf:"bytes,3,opt,name=modify,proto3,oneof"`
}

type InMessage_Cancel struct {
	Cancel *CancelOrderRequest `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

type InMessage_Massquote struct {
	Massquote *MassQuoteRequest `protobuf:"bytes,5,opt,name=massquote,proto3,oneof"`
}

type InMessage_Secdefreq struct {
	Secdefreq *SecurityDefinitionRequest `protobuf:"bytes,6,opt,name=secdefreq,proto3,oneof"`
}

type InMessage_Download struct {
	Download *DownloadRequest `protobuf:"bytes,7,opt,name=download,proto3,oneof"`
}

func (*InMessage_Login) isInMessage_Request() {}

func (*InMessage_Create) isInMessage_Request() {}

func (*InMessage_Modify) isInMessage_Request() {}

func (*InMessage_Cancel) isInMessage_Request() {}

func (*InMessage_Massquote) isInMessage_Request() {}

func (*InMessage_Secdefreq) isInMessage_Request() {}

func (*InMessage_Download) isInMessage_Request() {}

func (m *InMessage) GetRequest() isInMessage_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *InMessage) GetLogin() *LoginRequest {
	if x, ok := m.GetRequest().(*InMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (m *InMessage) GetCreate() *CreateOrderRequest {
	if x, ok := m.GetRequest().(*InMessage_Create); ok {
		return x.Create
	}
	return nil
}

func (m *InMessage) GetModify() *ModifyOrderRequest {
	if x, ok := m.GetRequest().(*InMessage_Modify); ok {
		return x.Modify
	}
	return nil
}

func (m *InMessage) GetCancel() *CancelOrderRequest {
	if x, ok := m.GetRequest().(*InMessage_Cancel); ok {
		return x.Cancel
	}
	return nil
}

func (m *InMessage) GetMassquote() *MassQuoteRequest {
	if x, ok := m.GetRequest().(*InMessage_Massquote); ok {
		return x.Massquote
	}
	return nil
}

func (m *InMessage) GetSecdefreq() *SecurityDefinitionRequest {
	if x, ok := m.GetRequest().(*InMessage_Secdefreq); ok {
		return x.Secdefreq
	}
	return nil
}

func (m *InMessage) GetDownload() *DownloadRequest {
	if x, ok := m.GetRequest().(*InMessage_Download); ok {
		return x.Download
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*InMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _InMessage_OneofMarshaler, _InMessage_OneofUnmarshaler, _InMessage_OneofSizer, []interface{}{
		(*InMessage_Login)(nil),
		(*InMessage_Create)(nil),
		(*InMessage_Modify)(nil),
		(*InMessage_Cancel)(nil),
		(*InMessage_Massquote)(nil),
		(*InMessage_Secdefreq)(nil),
		(*InMessage_Download)(nil),
	}
}

func _InMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*InMessage)
	// request
	switch x := m.Request.(type) {
	case *InMessage_Login:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Login); err != nil {
			return err
		}
	case *InMessage_Create:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Create); err != nil {
			return err
		}
	case *InMessage_Modify:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Modify); err != nil {
			return err
		}
	case *InMessage_Cancel:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cancel); err != nil {
			return err
		}
	case *InMessage_Massquote:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Massquote); err != nil {
			return err
		}
	case *InMessage_Secdefreq:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Secdefreq); err != nil {
			return err
		}
	case *InMessage_Download:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Download); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("InMessage.Request has unexpected type %T", x)
	}
	return nil
}

func _InMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*InMessage)
	switch tag {
	case 1: // request.login
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginRequest)
		err := b.DecodeMessage(msg)
		m.Request = &InMessage_Login{msg}
		return true, err
	case 2: // request.create
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateOrderRequest)
		err := b.DecodeMessage(msg)
		m.Request = &InMessage_Create{msg}
		return true, err
	case 3: // request.modify
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ModifyOrderRequest)
		err := b.DecodeMessage(msg)
		m.Request = &InMessage_Modify{msg}
		return true, err
	case 4: // request.cancel
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CancelOrderRequest)
		err := b.DecodeMessage(msg)
		m.Request = &InMessage_Cancel{msg}
		return true, err
	case 5: // request.massquote
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MassQuoteRequest)
		err := b.DecodeMessage(msg)
		m.Request = &InMessage_Massquote{msg}
		return true, err
	case 6: // request.secdefreq
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SecurityDefinitionRequest)
		err := b.DecodeMessage(msg)
		m.Request = &InMessage_Secdefreq{msg}
		return true, err
	case 7: // request.download
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DownloadRequest)
		err := b.DecodeMessage(msg)
		m.Request = &InMessage_Download{msg}
		return true, err
	default:
		return false, nil
	}
}

func _InMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*InMessage)
	// request
	switch x := m.Request.(type) {
	case *InMessage_Login:
		s := proto.Size(x.Login)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InMessage_Create:
		s := proto.Size(x.Create)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InMessage_Modify:
		s := proto.Size(x.Modify)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InMessage_Cancel:
		s := proto.Size(x.Cancel)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InMessage_Massquote:
		s := proto.Size(x.Massquote)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InMessage_Secdefreq:
		s := proto.Size(x.Secdefreq)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InMessage_Download:
		s := proto.Size(x.Download)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OutMessage struct {
	// Types that are valid to be assigned to Reply:
	//	*OutMessage_Login
	//	*OutMessage_Execrpt
	//	*OutMessage_Secdef
	//	*OutMessage_Reject
	Reply                isOutMessage_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OutMessage) Reset()         { *m = OutMessage{} }
func (m *OutMessage) String() string { return proto.CompactTextString(m) }
func (*OutMessage) ProtoMessage()    {}
func (*OutMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{1}
}
func (m *OutMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutMessage.Unmarshal(m, b)
}
func (m *OutMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutMessage.Marshal(b, m, deterministic)
}
func (dst *OutMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutMessage.Merge(dst, src)
}
func (m *OutMessage) XXX_Size() int {
	return xxx_messageInfo_OutMessage.Size(m)
}
func (m *OutMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OutMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OutMessage proto.InternalMessageInfo

type isOutMessage_Reply interface {
	isOutMessage_Reply()
}

type OutMessage_Login struct {
	Login *LoginReply `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type OutMessage_Execrpt struct {
	Execrpt *ExecutionReport `protobuf:"bytes,2,opt,name=execrpt,proto3,oneof"`
}

type OutMessage_Secdef struct {
	Secdef *SecurityDefinition `protobuf:"bytes,3,opt,name=secdef,proto3,oneof"`
}

type OutMessage_Reject struct {
	Reject *SessionReject `protobuf:"bytes,4,opt,name=reject,proto3,oneof"`
}

func (*OutMessage_Login) isOutMessage_Reply() {}

func (*OutMessage_Execrpt) isOutMessage_Reply() {}

func (*OutMessage_Secdef) isOutMessage_Reply() {}

func (*OutMessage_Reject) isOutMessage_Reply() {}

func (m *OutMessage) GetReply() isOutMessage_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *OutMessage) GetLogin() *LoginReply {
	if x, ok := m.GetReply().(*OutMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (m *OutMessage) GetExecrpt() *ExecutionReport {
	if x, ok := m.GetReply().(*OutMessage_Execrpt); ok {
		return x.Execrpt
	}
	return nil
}

func (m *OutMessage) GetSecdef() *SecurityDefinition {
	if x, ok := m.GetReply().(*OutMessage_Secdef); ok {
		return x.Secdef
	}
	return nil
}

func (m *OutMessage) GetReject() *SessionReject {
	if x, ok := m.GetReply().(*OutMessage_Reject); ok {
		return x.Reject
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*OutMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _OutMessage_OneofMarshaler, _OutMessage_OneofUnmarshaler, _OutMessage_OneofSizer, []interface{}{
		(*OutMessage_Login)(nil),
		(*OutMessage_Execrpt)(nil),
		(*OutMessage_Secdef)(nil),
		(*OutMessage_Reject)(nil),
	}
}

func _OutMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*OutMessage)
	// reply
	switch x := m.Reply.(type) {
	case *OutMessage_Login:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Login); err != nil {
			return err
		}
	case *OutMessage_Execrpt:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Execrpt); err != nil {
			return err
		}
	case *OutMessage_Secdef:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Secdef); err != nil {
			return err
		}
	case *OutMessage_Reject:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Reject); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("OutMessage.Reply has unexpected type %T", x)
	}
	return nil
}

func _OutMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*OutMessage)
	switch tag {
	case 1: // reply.login
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginReply)
		err := b.DecodeMessage(msg)
		m.Reply = &OutMessage_Login{msg}
		return true, err
	case 2: // reply.execrpt
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecutionReport)
		err := b.DecodeMessage(msg)
		m.Reply = &OutMessage_Execrpt{msg}
		return true, err
	case 3: // reply.secdef
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SecurityDefinition)
		err := b.DecodeMessage(msg)
		m.Reply = &OutMessage_Secdef{msg}
		return true, err
	case 4: // reply.reject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SessionReject)
		err := b.DecodeMessage(msg)
		m.Reply = &OutMessage_Reject{msg}
		return true, err
	default:
		return false, nil
	}
}

func _OutMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*OutMessage)
	// reply
	switch x := m.Reply.(type) {
	case *OutMessage_Login:
		s := proto.Size(x.Login)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OutMessage_Execrpt:
		s := proto.Size(x.Execrpt)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OutMessage_Secdef:
		s := proto.Size(x.Secdef)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OutMessage_Reject:
		s := proto.Size(x.Reject)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{3}
}
func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (dst *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(dst, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateOrderRequest struct {
	ClOrdId              int32                        `protobuf:"varint,1,opt,name=clOrdId,proto3" json:"clOrdId,omitempty"`
	Symbol               string                       `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price                float64                      `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             float64                      `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderType            CreateOrderRequest_OrderType `protobuf:"varint,5,opt,name=orderType,proto3,enum=protocol.CreateOrderRequest_OrderType" json:"orderType,omitempty"`
	OrderSide            CreateOrderRequest_OrderSide `protobuf:"varint,6,opt,name=orderSide,proto3,enum=protocol.CreateOrderRequest_OrderSide" json:"orderSide,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{4}
}
func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (dst *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(dst, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetClOrdId() int32 {
	if m != nil {
		return m.ClOrdId
	}
	return 0
}

func (m *CreateOrderRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CreateOrderRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateOrderRequest) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *CreateOrderRequest) GetOrderType() CreateOrderRequest_OrderType {
	if m != nil {
		return m.OrderType
	}
	return CreateOrderRequest_Market
}

func (m *CreateOrderRequest) GetOrderSide() CreateOrderRequest_OrderSide {
	if m != nil {
		return m.OrderSide
	}
	return CreateOrderRequest_Buy
}

type ModifyOrderRequest struct {
	ClOrdId              int32    `protobuf:"varint,1,opt,name=clOrdId,proto3" json:"clOrdId,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             float64  `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyOrderRequest) Reset()         { *m = ModifyOrderRequest{} }
func (m *ModifyOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyOrderRequest) ProtoMessage()    {}
func (*ModifyOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{5}
}
func (m *ModifyOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyOrderRequest.Unmarshal(m, b)
}
func (m *ModifyOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyOrderRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyOrderRequest.Merge(dst, src)
}
func (m *ModifyOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyOrderRequest.Size(m)
}
func (m *ModifyOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyOrderRequest proto.InternalMessageInfo

func (m *ModifyOrderRequest) GetClOrdId() int32 {
	if m != nil {
		return m.ClOrdId
	}
	return 0
}

func (m *ModifyOrderRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ModifyOrderRequest) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type CancelOrderRequest struct {
	ClOrdId              int32    `protobuf:"varint,1,opt,name=clOrdId,proto3" json:"clOrdId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderRequest) Reset()         { *m = CancelOrderRequest{} }
func (m *CancelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelOrderRequest) ProtoMessage()    {}
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{6}
}
func (m *CancelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderRequest.Unmarshal(m, b)
}
func (m *CancelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderRequest.Marshal(b, m, deterministic)
}
func (dst *CancelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderRequest.Merge(dst, src)
}
func (m *CancelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CancelOrderRequest.Size(m)
}
func (m *CancelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderRequest proto.InternalMessageInfo

func (m *CancelOrderRequest) GetClOrdId() int32 {
	if m != nil {
		return m.ClOrdId
	}
	return 0
}

type MassQuoteRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BidPrice             float64  `protobuf:"fixed64,2,opt,name=bidPrice,proto3" json:"bidPrice,omitempty"`
	BidQuantity          float64  `protobuf:"fixed64,3,opt,name=bidQuantity,proto3" json:"bidQuantity,omitempty"`
	AskPrice             float64  `protobuf:"fixed64,4,opt,name=askPrice,proto3" json:"askPrice,omitempty"`
	AskQuantity          float64  `protobuf:"fixed64,5,opt,name=askQuantity,proto3" json:"askQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MassQuoteRequest) Reset()         { *m = MassQuoteRequest{} }
func (m *MassQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*MassQuoteRequest) ProtoMessage()    {}
func (*MassQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{7}
}
func (m *MassQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MassQuoteRequest.Unmarshal(m, b)
}
func (m *MassQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MassQuoteRequest.Marshal(b, m, deterministic)
}
func (dst *MassQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MassQuoteRequest.Merge(dst, src)
}
func (m *MassQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_MassQuoteRequest.Size(m)
}
func (m *MassQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MassQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MassQuoteRequest proto.InternalMessageInfo

func (m *MassQuoteRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MassQuoteRequest) GetBidPrice() float64 {
	if m != nil {
		return m.BidPrice
	}
	return 0
}

func (m *MassQuoteRequest) GetBidQuantity() float64 {
	if m != nil {
		return m.BidQuantity
	}
	return 0
}

func (m *MassQuoteRequest) GetAskPrice() float64 {
	if m != nil {
		return m.AskPrice
	}
	return 0
}

func (m *MassQuoteRequest) GetAskQuantity() float64 {
	if m != nil {
		return m.AskQuantity
	}
	return 0
}

type SecurityDefinitionRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityDefinitionRequest) Reset()         { *m = SecurityDefinitionRequest{} }
func (m *SecurityDefinitionRequest) String() string { return proto.CompactTextString(m) }
func (*SecurityDefinitionRequest) ProtoMessage()    {}
func (*SecurityDefinitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{8}
}
func (m *SecurityDefinitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityDefinitionRequest.Unmarshal(m, b)
}
func (m *SecurityDefinitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityDefinitionRequest.Marshal(b, m, deterministic)
}
func (dst *SecurityDefinitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityDefinitionRequest.Merge(dst, src)
}
func (m *SecurityDefinitionRequest) XXX_Size() int {
	return xxx_messageInfo_SecurityDefinitionRequest.Size(m)
}
func (m *SecurityDefinitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityDefinitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityDefinitionRequest proto.InternalMessageInfo

func (m *SecurityDefinitionRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type DownloadRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{9}
}
func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (dst *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(dst, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

type SecurityDefinition struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	InstrumentID         int64    `protobuf:"varint,2,opt,name=instrumentID,proto3" json:"instrumentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityDefinition) Reset()         { *m = SecurityDefinition{} }
func (m *SecurityDefinition) String() string { return proto.CompactTextString(m) }
func (*SecurityDefinition) ProtoMessage()    {}
func (*SecurityDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{10}
}
func (m *SecurityDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityDefinition.Unmarshal(m, b)
}
func (m *SecurityDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityDefinition.Marshal(b, m, deterministic)
}
func (dst *SecurityDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityDefinition.Merge(dst, src)
}
func (m *SecurityDefinition) XXX_Size() int {
	return xxx_messageInfo_SecurityDefinition.Size(m)
}
func (m *SecurityDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityDefinition proto.InternalMessageInfo

func (m *SecurityDefinition) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SecurityDefinition) GetInstrumentID() int64 {
	if m != nil {
		return m.InstrumentID
	}
	return 0
}

type ExecutionReport struct {
	Symbol               string                       `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	ClOrdId              int32                        `protobuf:"varint,2,opt,name=clOrdId,proto3" json:"clOrdId,omitempty"`
	ExOrdId              string                       `protobuf:"bytes,3,opt,name=exOrdId,proto3" json:"exOrdId,omitempty"`
	OrderState           ExecutionReport_OrderState   `protobuf:"varint,4,opt,name=orderState,proto3,enum=protocol.ExecutionReport_OrderState" json:"orderState,omitempty"`
	ReportType           ExecutionReport_ReportType   `protobuf:"varint,5,opt,name=reportType,proto3,enum=protocol.ExecutionReport_ReportType" json:"reportType,omitempty"`
	Price                float64                      `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             float64                      `protobuf:"fixed64,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Remaining            float64                      `protobuf:"fixed64,8,opt,name=remaining,proto3" json:"remaining,omitempty"`
	LastPrice            float64                      `protobuf:"fixed64,9,opt,name=lastPrice,proto3" json:"lastPrice,omitempty"`
	LastQuantity         float64                      `protobuf:"fixed64,10,opt,name=lastQuantity,proto3" json:"lastQuantity,omitempty"`
	Side                 CreateOrderRequest_OrderSide `protobuf:"varint,11,opt,name=side,proto3,enum=protocol.CreateOrderRequest_OrderSide" json:"side,omitempty"`
	RejectReason         string                       `protobuf:"bytes,12,opt,name=rejectReason,proto3" json:"rejectReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ExecutionReport) Reset()         { *m = ExecutionReport{} }
func (m *ExecutionReport) String() string { return proto.CompactTextString(m) }
func (*ExecutionReport) ProtoMessage()    {}
func (*ExecutionReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{11}
}
func (m *ExecutionReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionReport.Unmarshal(m, b)
}
func (m *ExecutionReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionReport.Marshal(b, m, deterministic)
}
func (dst *ExecutionReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionReport.Merge(dst, src)
}
func (m *ExecutionReport) XXX_Size() int {
	return xxx_messageInfo_ExecutionReport.Size(m)
}
func (m *ExecutionReport) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionReport.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionReport proto.InternalMessageInfo

func (m *ExecutionReport) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ExecutionReport) GetClOrdId() int32 {
	if m != nil {
		return m.ClOrdId
	}
	return 0
}

func (m *ExecutionReport) GetExOrdId() string {
	if m != nil {
		return m.ExOrdId
	}
	return ""
}

func (m *ExecutionReport) GetOrderState() ExecutionReport_OrderState {
	if m != nil {
		return m.OrderState
	}
	return ExecutionReport_Booked
}

func (m *ExecutionReport) GetReportType() ExecutionReport_ReportType {
	if m != nil {
		return m.ReportType
	}
	return ExecutionReport_Status
}

func (m *ExecutionReport) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ExecutionReport) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *ExecutionReport) GetRemaining() float64 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *ExecutionReport) GetLastPrice() float64 {
	if m != nil {
		return m.LastPrice
	}
	return 0
}

func (m *ExecutionReport) GetLastQuantity() float64 {
	if m != nil {
		return m.LastQuantity
	}
	return 0
}

func (m *ExecutionReport) GetSide() CreateOrderRequest_OrderSide {
	if m != nil {
		return m.Side
	}
	return CreateOrderRequest_Buy
}

func (m *ExecutionReport) GetRejectReason() string {
	if m != nil {
		return m.RejectReason
	}
	return ""
}

type SessionReject struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionReject) Reset()         { *m = SessionReject{} }
func (m *SessionReject) String() string { return proto.CompactTextString(m) }
func (*SessionReject) ProtoMessage()    {}
func (*SessionReject) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_58c6893b63e17bd9, []int{12}
}
func (m *SessionReject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionReject.Unmarshal(m, b)
}
func (m *SessionReject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionReject.Marshal(b, m, deterministic)
}
func (dst *SessionReject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionReject.Merge(dst, src)
}
func (m *SessionReject) XXX_Size() int {
	return xxx_messageInfo_SessionReject.Size(m)
}
func (m *SessionReject) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionReject.DiscardUnknown(m)
}

var xxx_messageInfo_SessionReject proto.InternalMessageInfo

func (m *SessionReject) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*InMessage)(nil), "protocol.InMessage")
	proto.RegisterType((*OutMessage)(nil), "protocol.OutMessage")
	proto.RegisterType((*LoginRequest)(nil), "protocol.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "protocol.LoginReply")
	proto.RegisterType((*CreateOrderRequest)(nil), "protocol.CreateOrderRequest")
	proto.RegisterType((*ModifyOrderRequest)(nil), "protocol.ModifyOrderRequest")
	proto.RegisterType((*CancelOrderRequest)(nil), "protocol.CancelOrderRequest")
	proto.RegisterType((*MassQuoteRequest)(nil), "protocol.MassQuoteRequest")
	proto.RegisterType((*SecurityDefinitionRequest)(nil), "protocol.SecurityDefinitionRequest")
	proto.RegisterType((*DownloadRequest)(nil), "protocol.DownloadRequest")
	proto.RegisterType((*SecurityDefinition)(nil), "protocol.SecurityDefinition")
	proto.RegisterType((*ExecutionReport)(nil), "protocol.ExecutionReport")
	proto.RegisterType((*SessionReject)(nil), "protocol.SessionReject")
	proto.RegisterEnum("protocol.CreateOrderRequest_OrderType", CreateOrderRequest_OrderType_name, CreateOrderRequest_OrderType_value)
	proto.RegisterEnum("protocol.CreateOrderRequest_OrderSide", CreateOrderRequest_OrderSide_name, CreateOrderRequest_OrderSide_value)
	proto.RegisterEnum("protocol.ExecutionReport_OrderState", ExecutionReport_OrderState_name, ExecutionReport_OrderState_value)
	proto.RegisterEnum("protocol.ExecutionReport_ReportType", ExecutionReport_ReportType_name, ExecutionReport_ReportType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExchangeClient is the client API for Exchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExchangeClient interface {
	Connection(ctx context.Context, opts ...grpc.CallOption) (Exchange_ConnectionClient, error)
}

type exchangeClient struct {
	cc *grpc.ClientConn
}

func NewExchangeClient(cc *grpc.ClientConn) ExchangeClient {
	return &exchangeClient{cc}
}

func (c *exchangeClient) Connection(ctx context.Context, opts ...grpc.CallOption) (Exchange_ConnectionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Exchange_serviceDesc.Streams[0], "/protocol.Exchange/Connection", opts...)
	if err != nil {
		return nil, err
	}
	x := &exchangeConnectionClient{stream}
	return x, nil
}

type Exchange_ConnectionClient interface {
	Send(*InMessage) error
	Recv() (*OutMessage, error)
	grpc.ClientStream
}

type exchangeConnectionClient struct {
	grpc.ClientStream
}

func (x *exchangeConnectionClient) Send(m *InMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exchangeConnectionClient) Recv() (*OutMessage, error) {
	m := new(OutMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExchangeServer is the server API for Exchange service.
type ExchangeServer interface {
	Connection(Exchange_ConnectionServer) error
}

func RegisterExchangeServer(s *grpc.Server, srv ExchangeServer) {
	s.RegisterService(&_Exchange_serviceDesc, srv)
}

func _Exchange_Connection_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExchangeServer).Connection(&exchangeConnectionServer{stream})
}

type Exchange_ConnectionServer interface {
	Send(*OutMessage) error
	Recv() (*InMessage, error)
	grpc.ServerStream
}

type exchangeConnectionServer struct {
	grpc.ServerStream
}

func (x *exchangeConnectionServer) Send(m *OutMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exchangeConnectionServer) Recv() (*InMessage, error) {
	m := new(InMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Exchange_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Exchange",
	HandlerType: (*ExchangeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connection",
			Handler:       _Exchange_Connection_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "exchange.proto",
}

func init() { proto.RegisterFile("exchange.proto", fileDescriptor_exchange_58c6893b63e17bd9) }

var fileDescriptor_exchange_58c6893b63e17bd9 = []byte{
	// 891 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x5d, 0x6e, 0xdc, 0x36,
	0x10, 0x5e, 0xed, 0xbf, 0xc6, 0x4e, 0xa2, 0xb2, 0x41, 0xaa, 0x18, 0x41, 0x11, 0xb0, 0x3f, 0xc8,
	0x43, 0xb1, 0x68, 0x1d, 0xb4, 0x05, 0x02, 0xf4, 0xc5, 0xde, 0x04, 0x35, 0x10, 0xd7, 0x8e, 0xdc,
	0x03, 0x54, 0x96, 0xc6, 0x2e, 0x6b, 0xad, 0xb8, 0x26, 0x29, 0xd8, 0x7b, 0xa1, 0xa2, 0x47, 0xe9,
	0x5b, 0x4f, 0xd1, 0x7b, 0x14, 0x43, 0x6a, 0x45, 0x69, 0x17, 0x6b, 0x34, 0x4f, 0xc2, 0xcc, 0x7c,
	0xdf, 0x0c, 0x39, 0x7f, 0x14, 0x3c, 0xc6, 0xfb, 0xec, 0xf7, 0xb4, 0xbc, 0xc6, 0xd9, 0x52, 0x49,
	0x23, 0xd9, 0xd4, 0x7e, 0x32, 0x59, 0xf0, 0xbf, 0x06, 0x10, 0x9e, 0x94, 0xa7, 0xa8, 0x75, 0x7a,
	0x8d, 0x6c, 0x06, 0xa3, 0x42, 0x5e, 0x8b, 0x32, 0x0e, 0x5e, 0x06, 0xaf, 0xf6, 0x0e, 0x9f, 0xcd,
	0xd6, 0xb8, 0xd9, 0x7b, 0x52, 0x27, 0x78, 0x5b, 0xa1, 0x36, 0x3f, 0xf7, 0x12, 0x07, 0x63, 0x3f,
	0xc0, 0x38, 0x53, 0x98, 0x1a, 0x8c, 0xfb, 0x96, 0xf0, 0xc2, 0x13, 0x8e, 0xad, 0xfe, 0x4c, 0xe5,
	0xa8, 0x3c, 0xad, 0x46, 0x13, 0x6f, 0x21, 0x73, 0x71, 0xb5, 0x8a, 0x07, 0x9b, 0xbc, 0x53, 0xab,
	0xdf, 0xe4, 0x39, 0xb4, 0x8d, 0x97, 0x96, 0x19, 0x16, 0xf1, 0x70, 0x2b, 0x9e, 0xd5, 0x6f, 0xc5,
	0xb3, 0x5a, 0xf6, 0x06, 0xc2, 0x45, 0xaa, 0xf5, 0x6d, 0x25, 0x0d, 0xc6, 0x23, 0x4b, 0x3d, 0x68,
	0x85, 0x4c, 0xb5, 0xfe, 0x40, 0x26, 0x4f, 0xf4, 0x70, 0x76, 0x0c, 0xa1, 0xc6, 0x2c, 0xc7, 0x2b,
	0x85, 0xb7, 0xf1, 0xd8, 0x72, 0xbf, 0xf0, 0xdc, 0x0b, 0xcc, 0x2a, 0x25, 0xcc, 0x6a, 0x8e, 0x57,
	0xa2, 0x14, 0x46, 0xc8, 0x56, 0x92, 0x3c, 0x8f, 0xfd, 0x08, 0xd3, 0x5c, 0xde, 0x95, 0x85, 0x4c,
	0xf3, 0x78, 0x62, 0x7d, 0x3c, 0xf7, 0x3e, 0xe6, 0xb5, 0xc5, 0x33, 0x1b, 0xf0, 0x51, 0x08, 0x13,
	0xe5, 0xd4, 0xfc, 0xdf, 0x00, 0xe0, 0xac, 0x32, 0xeb, 0x5a, 0x7d, 0xd3, 0xad, 0xd5, 0xd3, 0xad,
	0x5a, 0x2d, 0x8b, 0x95, 0xaf, 0xd4, 0xf7, 0x30, 0xc1, 0x7b, 0xcc, 0xd4, 0xd2, 0xd4, 0xa5, 0x6a,
	0xc5, 0x7f, 0x7b, 0x8f, 0x59, 0xe5, 0x8e, 0xbe, 0x94, 0x8a, 0xe2, 0xaf, 0xb1, 0x94, 0x70, 0x77,
	0x89, 0xed, 0x42, 0x6d, 0xdf, 0x9c, 0x12, 0xee, 0xd0, 0xec, 0x3b, 0x18, 0x2b, 0xfc, 0x03, 0x33,
	0x53, 0x17, 0xea, 0xb3, 0x36, 0x4f, 0x6b, 0x1b, 0x8b, 0xcc, 0x44, 0x71, 0xc0, 0xa3, 0x09, 0x8c,
	0x14, 0x9d, 0x99, 0xbf, 0x83, 0xfd, 0x76, 0xb7, 0xb1, 0x03, 0x98, 0x56, 0x1a, 0x55, 0x99, 0x2e,
	0xd0, 0xde, 0x35, 0x4c, 0x1a, 0x99, 0x6c, 0xcb, 0x54, 0xeb, 0x3b, 0xa9, 0x72, 0x7b, 0xaf, 0x30,
	0x69, 0x64, 0xce, 0x01, 0x7c, 0x26, 0xd8, 0x53, 0x18, 0xa1, 0x52, 0x52, 0xd5, 0x30, 0x27, 0xf0,
	0xbf, 0xfb, 0xc0, 0xb6, 0x3b, 0x95, 0xc5, 0x30, 0xc9, 0xa8, 0x97, 0x4e, 0x72, 0x1b, 0x71, 0x94,
	0xac, 0x45, 0xf6, 0x0c, 0xc6, 0x7a, 0xb5, 0xb8, 0x94, 0x45, 0xed, 0xa7, 0x96, 0xc8, 0xfd, 0x52,
	0x89, 0x0c, 0x6d, 0x9e, 0x82, 0xc4, 0x09, 0x74, 0xbc, 0xdb, 0x2a, 0x2d, 0x8d, 0x30, 0x2b, 0x9b,
	0x88, 0x20, 0x69, 0x64, 0x36, 0x87, 0x50, 0x52, 0xcc, 0x5f, 0x57, 0x4b, 0xd7, 0x93, 0x8f, 0x0f,
	0xbf, 0x7e, 0x68, 0x7c, 0x66, 0x67, 0x6b, 0x74, 0xe2, 0x89, 0x8d, 0x97, 0x0b, 0x91, 0xa3, 0xed,
	0xce, 0xff, 0xe5, 0x85, 0xd0, 0x89, 0x27, 0x72, 0x0e, 0x61, 0xe3, 0x9d, 0x01, 0x8c, 0x4f, 0x53,
	0x75, 0x83, 0x26, 0xea, 0xb1, 0x10, 0x46, 0xef, 0xc5, 0x42, 0x98, 0x28, 0xe0, 0x9f, 0xd7, 0x18,
	0x22, 0xb0, 0x09, 0x0c, 0x8e, 0xaa, 0x55, 0xd4, 0x63, 0x53, 0x18, 0x5e, 0x60, 0x51, 0x44, 0x01,
	0xff, 0x0d, 0xd8, 0xf6, 0xec, 0x3e, 0x90, 0xc9, 0x26, 0x63, 0xfd, 0x5d, 0x19, 0x1b, 0x74, 0x33,
	0xc6, 0x67, 0xc0, 0xb6, 0xa7, 0x7c, 0x77, 0x04, 0xfe, 0x67, 0x00, 0xd1, 0xe6, 0x6c, 0xb7, 0x0a,
	0x18, 0x74, 0x0a, 0x78, 0x00, 0xd3, 0x4b, 0x91, 0x9f, 0xb7, 0x4e, 0xd4, 0xc8, 0xec, 0x25, 0xec,
	0x5d, 0x8a, 0xfc, 0x43, 0xf7, 0x5c, 0x6d, 0x15, 0xb1, 0x53, 0x7d, 0xe3, 0xd8, 0x75, 0xa1, 0xd7,
	0x32, 0xb1, 0x53, 0x7d, 0xd3, 0xb0, 0x47, 0x8e, 0xdd, 0x52, 0xf1, 0xd7, 0xf0, 0x7c, 0xe7, 0x1e,
	0xd9, 0x75, 0x60, 0xfe, 0x09, 0x3c, 0xd9, 0x58, 0x1c, 0xfc, 0x1c, 0xd8, 0xb6, 0x9f, 0x9d, 0x37,
	0xe6, 0xb0, 0x2f, 0x4a, 0x6d, 0x54, 0xb5, 0xc0, 0xd2, 0x9c, 0xcc, 0xed, 0xad, 0x07, 0x49, 0x47,
	0xc7, 0xff, 0x19, 0xc2, 0x93, 0x8d, 0xf5, 0x40, 0xfe, 0x2e, 0x3a, 0xfe, 0x9c, 0xd4, 0x2e, 0x44,
	0xbf, 0x5b, 0xea, 0x98, 0x96, 0x8f, 0xb3, 0x0c, 0x2c, 0x65, 0x2d, 0xb2, 0x39, 0x80, 0xeb, 0x42,
	0x43, 0x8f, 0xc8, 0xd0, 0xf6, 0xef, 0x97, 0x3b, 0x37, 0x53, 0xdd, 0xbc, 0x84, 0x4d, 0x5a, 0x3c,
	0xf2, 0xa2, 0x2c, 0xa0, 0x35, 0x4b, 0x0f, 0x78, 0x49, 0x1a, 0x6c, 0xd2, 0xe2, 0xf9, 0x86, 0x1c,
	0xef, 0x6a, 0xc8, 0xc9, 0xc6, 0x08, 0xbf, 0x80, 0x50, 0xe1, 0x22, 0x15, 0xa5, 0x28, 0xaf, 0xe3,
	0xa9, 0x35, 0x7a, 0x05, 0x59, 0x8b, 0x54, 0x1b, 0xd7, 0x14, 0xa1, 0xb3, 0x36, 0x0a, 0xca, 0x3e,
	0x09, 0x4d, 0x5b, 0x80, 0x05, 0x74, 0x74, 0xec, 0x0d, 0x0c, 0x35, 0xcd, 0xf5, 0xde, 0x47, 0xcd,
	0xb5, 0xe5, 0x90, 0x7f, 0xb7, 0x58, 0x13, 0x4c, 0xb5, 0x2c, 0xe3, 0x7d, 0x9b, 0xf8, 0x8e, 0x8e,
	0xff, 0x02, 0xe0, 0x33, 0x4a, 0x73, 0x7f, 0x24, 0xe5, 0x0d, 0xe6, 0x51, 0x8f, 0xed, 0xc3, 0xd4,
	0x2d, 0x68, 0xcc, 0xa3, 0x80, 0xed, 0xc1, 0xe4, 0x3c, 0x55, 0x46, 0xa4, 0x45, 0xd4, 0x27, 0xd8,
	0x3b, 0x51, 0x14, 0x98, 0x47, 0x03, 0xf6, 0x08, 0x42, 0x37, 0x91, 0x24, 0x0e, 0x69, 0xe3, 0xfa,
	0xdc, 0x12, 0x90, 0x1c, 0x57, 0xda, 0xad, 0x09, 0x22, 0x45, 0x01, 0xff, 0x0a, 0x1e, 0x75, 0x5e,
	0x00, 0xbf, 0x98, 0x83, 0xd6, 0x62, 0x3e, 0x3c, 0x81, 0xe9, 0xdb, 0xfa, 0x9f, 0x85, 0xfd, 0x04,
	0x70, 0x2c, 0xcb, 0x12, 0x33, 0xdb, 0xce, 0x9f, 0xfa, 0x34, 0x34, 0x3f, 0x2e, 0x07, 0xad, 0xd7,
	0xcf, 0x3f, 0x91, 0xbc, 0xf7, 0x2a, 0xf8, 0x36, 0xb8, 0x1c, 0x5b, 0xd3, 0xeb, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x17, 0x62, 0x46, 0x64, 0x05, 0x09, 0x00, 0x00,
}
